### ISSUE TITLE
Error when running the training script

### ISSUE THREAD

**Issue by saraalemadi** [thuml/CLIPood#7]
Hi,
I am getting the error below when attempting to run the following training command:

`python main.py DomainBed/domainbed/data/ -d PACS --task domain_shift --targets 0  -b 12 --lr 5e-6 --epochs 10 --lam 0.3 --beta 0.5`

```
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    main(args)
  File "main.py", line 73, in main
    best_val_acc1 = evaluate_all(classifier, val_loader, train_text_features, test_loaders, args, writer, device)
  File "CLIPood/CLIPood-main/engine.py", line 249, in evaluate_all
    val_acc1 = validate(val_loader, model, train_text_features, args, device)
  File "CLIPood/CLIPood-main/engine.py", line 226, in validate
    image_features = model(images)
  File "anaconda3/envs/clipood/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "anaconda3/envs/clipood/lib/python3.8/site-packages/clip/model.py", line 224, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "anaconda3/envs/clipood/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "anaconda3/envs/clipood/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "anaconda3/envs/clipood/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
```

**Comment by GXZlegend** [comment]
Thanks. This is caused by a missing of type conversion (perhaps a bug) of CLIP's original repo. We have reported in [this issue](https://github.com/openai/CLIP/issues/386). Please refer to the newest `README.md` for fixing.
